language: node_js

node_js:
  - "10.13.0"


matrix:
  include:
  - name: "Linux"
    os: linux
    dist: xenial
    sudo: false
    before_install:
      - export DISPLAY=:99
      - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - name: "MacOS"
    os: osx
    script:
      - otool -L /Users/travis/build/node-3d/qml-raub/bin-mac64/qml.node
      - otool -L /Users/travis/build/node-3d/qml-raub/node_modules/deps-qmlui-raub/bin-mac64/libqmlui.dylib
      - chmod +x ./unsign
      # - codesign --remove-signature
      # - ./unsign /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-qml-raub/bin-mac64/QtQuick
      - ../unsign /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-qml-raub/bin-mac64/QtQml
      - ../unsign /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-qml-raub/bin-mac64/QtQuick
      - ../unsign /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-qml-raub/bin-mac64/QtQuickControls2
      - ../unsign /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-qml-raub/bin-mac64/QtQuickTemplates2
      - ../unsign /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-qml-raub/bin-mac64/QtQuickWidgets
      - ../unsign /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-gui-raub/bin-mac64/QtGui
      - ../unsign /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-gui-raub/bin-mac64/QtWidgets
      - ../unsign /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-core-raub/bin-mac64/QtCore
      - ../unsign /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-core-raub/bin-mac64/QtNetwork
      - ../unsign /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-core-raub/bin-mac64/QtDBus
      - LD_DEBUG=libs DYLD_PRINT_LIBRARIES=1 node test
      # - echo OK.
  - name: "Windows"
    os: windows
    script:
      - echo OK.


install:
  - cd test
  - npm i
