language: node_js

node_js:
  - "10.13.0"


matrix:
  include:
  # - name: "Linux"
  #   os: linux
  #   dist: xenial
  #   sudo: false
  #   before_install:
  #     - export DISPLAY=:99
  #     - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - name: "MacOS"
    os: osx
    env:
      - OSXBUILD=true
    script:
      - install_name_tool -add_rpath /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-core-raub/bin-mac64 /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-gui-raub/bin-mac64/plugins/platforms/libqcocoa.dylib
      - install_name_tool -add_rpath /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-gui-raub/bin-mac64 /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-gui-raub/bin-mac64/plugins/platforms/libqcocoa.dylib
      - npm test
  # - name: "Windows"
  #   os: windows
  #   script:
  #     - echo OK.


install:
  - cd test
  - npm i


deploy:
  on:
    all_branches: true
    condition: $OSXBUILD = true
  provider: releases
  name: "Binary for OSX"
  body: $TRAVIS_COMMIT_MESSAGE
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  overwrite: true
  draft: true
  file:
    - /Users/travis/build/node-3d/qml-raub/node_modules/deps-qt-gui-raub/bin-mac64/plugins/platforms/libqcocoa.dylib
