name: Test
defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit Tests
    strategy:
        matrix:
          os: [ubuntu-22.04, windows-2022, macos-14]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
          cache: 'npm'

      - name: Install Modules
        run: npm ci

      - name: Build Current Binary
        run: npm run build

      - name: Run Unit Tests - Linux
        if: matrix.os == 'ubuntu-22.04'
        run: |
          # patchelf --force-rpath --set-rpath '$ORIGIN:$ORIGIN/../node_modules/deps-qt-core-raub/bin-linux:$ORIGIN/../node_modules/deps-qt-gui-raub/bin-linux:$ORIGIN/../node_modules/deps-qt-qml-raub/bin-linux:$ORIGIN/../../deps-qt-core-raub/bin-linux:$ORIGIN/../../deps-qt-gui-raub/bin-linux:$ORIGIN/../../deps-qt-qml-raub/bin-linux' $GITHUB_WORKSPACE/node_modules/deps-qmlui-raub/bin-linux/libqmlui.so
          sudo apt-get update -qq
          sudo apt-get install -qq libgles2-mesa-dev libxcb-cursor0 libxcb-icccm4 libxcb-keysyms1 libxcb-shape0 libxcb-xkb1 libxkbcommon-x11-0
          # LD_DEBUG=libs xvfb-run --auto-servernum npm run test-ci
          xvfb-run --auto-servernum npm run test-ci

      # - name: Run Unit Tests - MacOS
      #   if: matrix.os == 'macos-14'
      #   run: npm run test-ci
